432 wizardjs1 uncaught typeerror cryptorandomuuid is not a function (#448)
* Refactor element-util.ts and common.ts

- Import generateUUID from @dhruv-techapps/core-common
- Replace crypto.randomUUID() with generateUUID() for generating UUIDs
- Remove unused RANDOM_UUID type from common.ts
- Update imports in action-model.ts and config-model.ts to use generateUUID from @dhruv-techapps/core-common
- Update imports in notifications.service.ts to use generateUUID from @dhruv-techapps/core-common
- Update imports in google-analytics-background.ts and sandbox.ts to use generateUUID from @dhruv-techapps/core-common

* Refactor imports in action-table.tsx and remove-configs.modal.tsx

* Add @dhruv-techapps/core-common as a peer dependency in google-analytics package.json